const products = [
    {
        id: 1,
        name: "SAMSUNG Galaxy Watch 3 (41mm, GPS, Bluetooth) Smart Watch with Advanced Health Monitoring, Fitness Tracking, and Long Lasting Battery - Mystic Silver (US Version)",
        description: [
            "STYLE YOU CAN COUNT ON: Galaxy Watch3 combines style—two sizes, two finishes, three colors and, 50,000 plus watch faces-with military-grade durability and water resistance",
            "LEAVE YOUR PHONE BEHND: Galaxy Watch3 gives you the freedom to call, text, stream music and get notifications via Bluetooth connectivity",
            "You can share the PDF report of your ECG recording with your health care provider using the Samsung Health Monitor app on your compatible Galaxy phone",
            "BATTERY BUILT FOR ENDURANCE: The Galaxy Watch3’s long-lasting battery can go for more than a day on a single charge, and you can always get a quick boost from your compatible Galaxy phone with Wireless Power Share",
            "STRONGER INSIGHTS. NEXT-LEVEL FITNESS: Spend your time moving while Galaxy Watch3 tracks seven popular activities automatically. Get more out of each movement thanks to built-in run coaching",
            "LEVEL UP YOUR DOWNTIME: Galaxy Watch3’s automatic sleep tracker offers insights on how to get a better night’s sleep. It also monitors your stress level and helps you recenter with breathing guides",
            "SMART WATCH. SMART LIFE: Integrated Bixby voice functionality can read your texts, make a call or initiate coaching on command and on the go. Samsung Pay lets you leave home without a wallet. And a multilayered defense-grade security platform keeps all your data safe.",
            "ANDROID/iOS COMPATIBLE: Pairs seamlessly with Android devices and select iOS devices",
        ],
        image: "https://image-us.samsung.com/SamsungUS/home/mobile/wearables/smartwatches/pdp/gwa-3/gallery/sm-r845uzkaxar/gallery-01-110557-lte_sm-r840_galaxy_watch_3_45mm_mystic_black_v_front-1600x1200.jpg?$product-details-jpg$",
        price: 35099,
        rating: 4,
    },
    {
        id: 2,
        name: "Oculus Rift S PC-Powered VR Gaming Headset",
        description: [
            "Top VR gaming library: Blast, slash and soar your way through the top library in VR gaming. Oculus Rift S lets you play hundreds of games and exclusives already available in the Oculus store, with so much more to come.",
            "Improved optics: Stare down the competition with next-generation lenses and a sharper display. Improved optics deliver bright, vivid colors and reduced “screen-door” effect.",
            "Ergonomic design: Keep your head in the game thanks to a Halo headband redesigned with speed in mind. Rift S stays securely and comfortably in place with a quick twist of the fit wheel, so it can take-or double take-your fastest reactions.",
            "Oculus touch controllers: Arm yourself with our updated Oculus touch controllers. Your slashes, throws and grab appear in VR with intuitive, realistic precision, transporting your hands and gestures right into the game.",
            "Oculus insight tracking: take a step forward with Oculus insight. It translates your movements into VR No matter which way you're facing and provides room-scale tracking without external sensors.",
            "Oculus Rift S requires your Facebook account to log in, making it easy to meet up with friends in VR and discover communities around the world.",
        ],
        image: "https://m.media-amazon.com/images/I/71URNvzoWqL._SX522_.jpg",
        price: 50000,
        rating: 5,
    },
    {
        id: 3,
        name: "SAMSUNG 65-Inch Class Crystal UHD AU8000 Series - 4K UHD HDR Smart TV with Alexa Built-in (UN65AU8000FXZA, 2021 Model)",
        description: [
            "DYNAMIC CRYSTAL COLOR: A fine crystal layer reveals millions of true-to-life colors.",
            "CRYSTAL PROCESSOR 4K: Intelligent, ultra-fast optimization of 4K content.",
            "SMART TV WITH MULTIPLE VOICE ASSISTANTS: Access apps and streaming services right on your TV with your voice.",
            "3 HDMI PORTS: Connect up to 3 devices with HDMI.",
            "HDR: Unveils shades of color that go beyond HDTV.",
        ],
        image: "https://m.media-amazon.com/images/I/71LJJrKbezL._AC_SL1500_.jpg",
        price: 99999,
        rating: 4,
    },
    {
        id: 4,
        name: "Ergousit Ergonomic Office Chair -Mesh Computer Chair with Adjustable 3D Armrest, Lumbar Support and Headrest - Rolling Desk Chair, Gaming Chairs, Executive Swivel Chair for Home and Office(Black)",
        description: [
            "Conforms to you: With it’s 3D Adjustable Armrest and Lumbar System, ElastoMesh, 135 Degree Back Tilt, The ergonomic design conforms to the human body curve, allowing you to maintain a comfortable and healthy posture at all times, – it’s easy to think the Ergo3D is from the future, but instead it’s evolved Ergo Seating at its finest and it’s here now.",
            "Ease into Work, or Play: Mesh Headrest adjusts up and down while the 3D Adjust Arms go forwards, back, up, down, side to side, and rotate for the best fit to your body. and Lumbar System which creates total spinal support, arched seat cushion design reduces the pressure on the legs, Made with breathable Mesh adjustable headrest, up/down motion for adjustable height Can meet the needs of different scenarios.",
            "Soft HD Mesh Office Chair: Our breathable ElastoMesh provides optimal airflow to avoid sweating and sticking. But it’s also smooth, and nothing like sitting on wire like many of the chairs you’ll see today. And while it’s good to take regular breaks, the Ergo3D is so comfy you’ll forget you’re even working.",
            "Heavy Duty: Our 5-Point Base with dual castors gives greater stability and strength over common 4-Point, single castor chairs. And our strong aluminum base makes this heavy-duty office chair ideal for adults up to 275 lb.",
            "5-Year Warranty: All task chairs come with 5 year after-sale support, If there is any issue, please contact us directly through your order,we will provide you a 100% satisfied solution.",
        ],
        image: "https://m.media-amazon.com/images/I/71ew7578U0L._AC_SL1500_.jpg",
        price: 20599,
        rating: 4,
    },
    {
        id: 5,
        name: "Adidas Men's Ultraboost 20 Sneaker",
        description: [
            "100% Textile",
            "Synthetic sole",
            "Shaft measures approximately low-top from arch",
            "Sock, snug-like fit",
            "Adaptive, energised running shoes",
            "Responsive Boost midsole",
        ],
        image: "https://www.shooos.com/media/catalog/product/cache/2/image/9df78eab33525d08d6e5fb8d27136e95/a/d/adidas-ultraboost-20-eg06911_1.jpg",
        price: 31379,
        rating: 5,
    },
    {
        id: 6,
        name: "HyperX Cloud Stinger – Gaming Headset, Lightweight, Comfortable Memory Foam, Swivel to Mute Noise-Cancellation Microphone, Works on PC, PS4, PS5, Xbox One, Xbox Series X|S, Nintendo Switch and Mobile",
        description: [
            "Lightweight headset (275 gram) with 90-degree rotating ear cups provide a snug fit that conforms to your head",
            "50 millimeter directional drivers for audio precision — enjoy the full audioscape of your favorite games",
            "HyperX signature memory foam provides maximum comfort during extended use",
            "Adjustable steel slider for a solid and long lasting sturdy feel",
            "Intuitive volume control on headset ear cup",
            "Swivel-to-mute noise-cancellation microphone so you’ll always know when you’re muted",
            "Multi-platform compatibility: PC, PS4, Xbox One, Nintendo Switch and more",
            "Refer user guide on technical specification before use",
        ],
        image: "https://m.media-amazon.com/images/I/51kxIEmO+ZL._AC_SL1286_.jpg",
        price: 4199,
        rating: 4,
    },
];

export default products;
